### ISSUE TITLE
[Pratybų svetainė]: netikslumas → taisymas (rašybos klaida)

### ISSUE THREAD

**Issue by Vytele** [mokymai/taisymai-2022#33]
1. **Dalykas:** BS-2022
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** file:///C:/Users/Lenovo/Downloads/2_savaite/2_savaite.Manipuliavimas_R_objektais.html 
5. **Glaustai aprašykite netikslumą:** rašybos klaida
6. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Tai yra normalu ir atidžiau paskaičius pastebėtumėt, kad tai nėra klaudos žinutės.
7. **Netikslumo tekstas:** klaudos
8. **Siūlomas taisymo tekstas:** klaidos 
9. **Ekrano nuotrauka („Screenshots“)**  
<img width="647" alt="image" src="https://user-images.githubusercontent.com/112801376/189938735-0bd65bec-b7ee-45bf-a1ab-6d771ac335b8.png">

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
@VitaT, gal tai tavo pratybos?

**Comment by VitaT** [comment]
panašu, kad taip. Dėkui
