### ISSUE TITLE
[Pratybų svetainė]: konkrečią → konkrečią funkciją (praleistas žodis "funkciją")

### ISSUE THREAD

**Issue by SalciuS** [mokymai/taisymai-2022#71]
1. **Dalykas:** BS-2022
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/pratybos-2022/s02.html
4. **Glaustai aprašykite netikslumą:**  praleistas žodis "funkciją". Skaitant nuosekliai ankstesnius sakinius galima nuspėti žodį, bet reikia papildomo laiko susigaudyti. 

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Tad norėdami pasirinkti konkrečią 
6. **Netikslumo tekstas:** Tad norėdami pasirinkti konkrečią, galime naudoti vieną iš šių kodo variantų:
7. **Siūlomas taisymo tekstas:** Tad norėdami pasirinkti konkrečią *funkciją*, galime naudoti vieną iš šių kodo variantų:
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/99132902/154953740-e6010457-0266-43ad-9751-3247a23d12ab.png)

...

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Tai stiliaus dalykas. Žodis neįrašytas sąmoningai, nes iš konteksto aišku, apie ką kalbama.
