### ISSUE TITLE
[Teorijos svetainė]: neužkraunamas "3. Tyrimų planavimas" temos skilties 3.1 pav

### ISSUE THREAD

**Issue by deshrius** [mokymai/taisymai-2022#88]
1. **Dalykas:** BS-2022 
2. **Netikslumo vieta:** Biostatistikos teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/tyrimu-planavimas.html#paklaidos-ir-tikslumas
4. **Glaustai aprašykite netikslumą:**  Neužkraunamas 3.1 paveikslėlis naudojant kompiuterinę MicrosoftEdge naršyklės versiją

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** --- 
6. **Netikslumo tekstas:** ---
7. **Siūlomas taisymo tekstas:** ---
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/99125968/159115527-9fbca058-ba3a-4fe6-b91e-0fa283ac9f77.png)
![image](https://user-images.githubusercontent.com/99125968/159115553-5fa32bb9-06e7-4340-8a6d-e612e59ae448.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Gali būti, kad jūsų kompiuteryje tai blokuoja ugniasienė, antivirusinė programa arba prastas interneto ryšys.
