### ISSUE TITLE
[Biostatistika]: neveikianti nuoroda į Čekanavičiaus vadovėlio skyrių apie PI

### ISSUE THREAD

**Issue by KarolinaM2** [mokymai/taisymai-2022#99]
1. **Dalykas:** BS-2022 
2. **Netikslumo vieta:** Biostatistikos teorijos svetainė (`mokymai.github.io/biostatistika`), 10-as skyrius PI.
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/pi.html
4. **Glaustai aprašykite netikslumą:**  Nuoroda į papildomą medžiagą apie pasikliautinuosius intervalus Čekanavičiaus vadovėlyje neveikia.
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Apie tai, kas yra pasikliautinieji intervalai, plačiau paaiškinta šaltinio
7. **Siūlomas taisymo tekstas:** *veikianti nuoroda arba kreipinio į ją panaikinimas*
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/99139281/167309666-87a34377-5b8e-4a01-9289-ae58d25abba0.png)

![image](https://user-images.githubusercontent.com/99139281/167309756-de4e3e69-b9db-458d-834e-8ab94e893e18.png)

Patvirtinkite pažymėdami [x]:

- [X] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [X] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [X] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [X] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Deja, resursas buvo uždarytas.
